
$("#status-0").keypress(function(e){
	setcomment("status-0",e);
});
$("#status-1").keypress(function(e){
	setcomment("status-1",e);
});
$("#status-2").keypress(function(e){
	setcomment("status-2",e);
});
$("#status-3").keypress(function(e){
	setcomment("status-3",e);
});
$("#status-4").keypress(function(e){
	setcomment("status-4",e);
});
$("#status-5").keypress(function(e){
	setcomment("status-5",e);
});
$("#status-6").keypress(function(e){
	setcomment("status-6",e);
});
$("#status-7").keypress(function(e){
	setcomment("status-7",e);
});
$("#status-8").keypress(function(e){
	setcomment("status-8",e);
});
$("#status-9").keypress(function(e){
	setcomment("status-9",e);
});
$("#status-10").keypress(function(e){
	setcomment("status-10",e);
});
$("#status-11").keypress(function(e){
	setcomment("status-11",e);
});
$("#status-12").keypress(function(e){
	setcomment("status-12",e);
});
$("#status-13").keypress(function(e){
	setcomment("status-13",e);
});
$("#status-14").keypress(function(e){
	setcomment("status-14",e);
});
$("#status-15").keypress(function(e){
	setcomment("status-15",e);
});
$("#status-16").keypress(function(e){
	setcomment("status-16",e);
});
$("#status-17").keypress(function(){
	setcomment("status-17",e);
});
$("#status-18").keypress(function(e){
	setcomment("status-18",e);
});
$("#status-19").keypress(function(e){
	setcomment("status-19",e);
});
$("#status-20").keypress(function(e){
	setcomment("status-20",e);
});
$("#status-21").keypress(function(e){
	setcomment("status-21",e);
});
$("#status-22").keypress(function(e){
	setcomment("status-22",e);
});
$("#status-23").keypress(function(e){
	setcomment("status-23",e);
});
$("#status-24").keypress(function(e){
	setcomment("status-24",e);
});
$("#status-25").keypress(function(e){
	setcomment("status-25",e);
});
$("#status-26").keypress(function(e){
	setcomment("status-26",e);
});
$("#status-27").keypress(function(e){
	setcomment("status-27",e);
});
$("#status-28").keypress(function(e){
	setcomment("status-28",e);
});
$("#status-29").keypress(function(e){
	setcomment("status-29",e);
});
$("#status-30").keypress(function(e){
	setcomment("status-30",e);
});
$("#status-31").keypress(function(e){
	setcomment("status-31",e);
});
$("#status-32").keypress(function(e){
	setcomment("status-32",e);
});
$("#status-33").keypress(function(e){
	setcomment("status-33",e);
});
$("#status-34").keypress(function(e){
	setcomment("status-34",e);
});
$("#status-35").keypress(function(e){
	setcomment("status-35",e);
});
$("#status-36").keypress(function(e){
	setcomment("status-36",e);
});
$("#status-37").keypress(function(e){
	setcomment("status-37",e);
});
$("#status-38").keypress(function(e){
	setcomment("status-38",e);
});
$("#status-39").keypress(function(e){
	setcomment("status-39",e);
});
$("#status-40").keypress(function(e){
	setcomment("status-40",e);
});
$("#status-41").keypress(function(e){
	setcomment("status-41",e);
});
$("#status-42").keypress(function(e){
	setcomment("status-42",e);
});
$("#status-43").keypress(function(e){
	setcomment("status-43",e);
});
$("#status-44").keypress(function(e){
	setcomment("status-44",e);
});
$("#status-45").keypress(function(e){
	setcomment("status-45",e);
});
$("#status-46").keypress(function(e){
	setcomment("status-46",e);
});
$("#status-47").keypress(function(e){
	setcomment("status-47",e);
});
$("#status-48").keypress(function(e){
	setcomment("status-48",e);
});
$("#status-49").keypress(function(e){
	setcomment("status-49",e);
});
$("#status-50").keypress(function(e){
	setcomment("status-50",e);
});
$("#like-0").click(function(){
	setlike("like-0");
});
$("#like-1").click(function(){
	setlike("like-1");
});
$("#like-2").click(function(){
	setlike("like-2");
});
$("#like-3").click(function(){
	setlike("like-3");
});
$("#like-4").click(function(){
	setlike("like-4");
});
$("#like-5").click(function(){
	setlike("like-5");
});
$("#like-6").click(function(){
	setlike("like-6");
});
$("#like-7").click(function(){
	setlike("like-7");
});
$("#like-8").click(function(){
	setlike("like-8");
});
$("#like-9").click(function(){
	setlike("like-9");
});
$("#like-10").click(function(){
	setlike("like-10");
});
$("#like-11").click(function(){
	setlike("like-11");
});
$("#like-12").click(function(){
	setlike("like-12");
});
$("#like-13").click(function(){
	setlike("like-13");
});
$("#like-14").click(function(){
	setlike("like-14");
});
$("#like-15").click(function(){
	setlike("like-15");
});
$("#like-16").click(function(){
	setlike("like-16");
});
$("#like-17").click(function(){
	setlike("like-17");
});
$("#like-18").click(function(){
	setlike("like-18");
});
$("#like-19").click(function(){
	setlike("like-19");
});
$("#like-20").click(function(){
	setlike("like-20");
});
$("#like-21").click(function(){
	setlike("like-21");
});
$("#like-22").click(function(){
	setlike("like-22");
});
$("#like-23").click(function(){
	setlike("like-23");
});
$("#like-24").click(function(){
	setlike("like-24");
});
$("#like-25").click(function(){
	setlike("like-25");
});
$("#like-26").click(function(){
	setlike("like-26");
});
$("#like-27").click(function(){
	setlike("like-27");
});
$("#like-28").click(function(){
	setlike("like-28");
});
$("#like-29").click(function(){
	setlike("like-29");
});
$("#like-30").click(function(){
	setlike("like-30");
});
$("#like-31").click(function(){
	setlike("like-31");
});
$("#like-32").click(function(){
	setlike("like-32");
});
$("#like-33").click(function(){
	setlike("like-33");
});
$("#like-34").click(function(){
	setlike("like-34");
});
$("#like-35").click(function(){
	setlike("like-35");
});
$("#like-36").click(function(){
	setlike("like-36");
});
$("#like-37").click(function(){
	setlike("like-37");
});
$("#like-38").click(function(){
	setlike("like-38");
});
$("#like-39").click(function(){
	setlike("like-39");
});
$("#like-40").click(function(){
	setlike("like-40");
});
$("#like-41").click(function(){
	setlike("like-41");
});
$("#like-42").click(function(){
	setlike("like-42");
});
$("#like-43").click(function(){
	setlike("like-43");
});
$("#like-44").click(function(){
	setlike("like-44");
});
$("#like-45").click(function(){
	setlike("like-45");
});
$("#like-46").click(function(){
	setlike("like-46");
});
$("#like-47").click(function(){
	setlike("like-47");
});
$("#like-48").click(function(){
	setlike("like-48");
});
$("#like-49").click(function(){
	setlike("like-49");
});
$("#like-50").click(function(){
	setlike("like-50");
});
$("#cmnt-0").click(function(){
	viewcomment("0");
});
$("#cmnt-1").click(function(){
	viewcomment("1");
});
$("#cmnt-2").click(function(){
	viewcomment("2");
});
$("#cmnt-3").click(function(){
	viewcomment("3");
});
$("#cmnt-4").click(function(){
	viewcomment("4");
});
$("#cmnt-5").click(function(){
	viewcomment("5");
});
$("#cmnt-6").click(function(){
	viewcomment("6");
});
$("#cmnt-7").click(function(){
	viewcomment("cmnt-7");
});
$("#cmnt-8").click(function(){
	viewcomment("8");
});
$("#cmnt-9").click(function(){
	viewcomment("9");
});
$("#cmnt-10").click(function(){
	viewcomment("10");
});
$("#cmnt-11").click(function(){
	viewcomment("11");
});
$("#cmnt-12").click(function(){
	viewcomment("12");
});
$("#cmnt-13").click(function(){
	viewcomment("13");
});
$("#cmnt-14").click(function(){
	viewcomment("14");
});
$("#cmnt-15").click(function(){
	viewcomment("15");
});
$("#cmnt-16").click(function(){
	viewcomment("16");
});
$("#cmnt-17").click(function(){
	viewcomment("17");
});
$("#cmnt-18").click(function(){
	viewcomment("18");
});
$("#cmnt-19").click(function(){
	viewcomment("19");
});
$("#cmnt-20").click(function(){
	viewcomment("20");
});
$("#cmnt-21").click(function(){
	viewcomment("21");
});
$("#cmnt-22").click(function(){
	viewcomment("22");
});
$("#cmnt-23").click(function(){
	viewcomment("23");
});
$("#cmnt-24").click(function(){
	viewcomment("24");
});
$("#cmnt-25").click(function(){
	viewcomment("25");
});
$("#cmnt-26").click(function(){
	viewcomment("26");
});
$("#cmnt-27").click(function(){
	viewcomment("27");
});
$("#cmnt-28").click(function(){
	viewcomment("28");
});
$("#cmnt-29").click(function(){
	viewcomment("29");
});
$("#cmnt-30").click(function(){
	viewcomment("30");
});
$("#cmnt-31").click(function(){
	viewcomment("31");
});
$("#cmnt-32").click(function(){
	viewcomment("32");
});
$("#cmnt-33").click(function(){
	viewcomment("33");
});
$("#cmnt-34").click(function(){
	viewcomment("34");
});
$("#cmnt-35").click(function(){
	viewcomment("35");
});
$("#cmnt-36").click(function(){
	viewcomment("36");
});
$("#cmnt-37").click(function(){
	viewcomment("37");
});
$("#cmnt-38").click(function(){
	viewcomment("38");
});
$("#cmnt-39").click(function(){
	viewcomment("39");
});
$("#cmnt-40").click(function(){
	viewcomment("40");
});
$("#cmnt-41").click(function(){
	viewcomment("41");
});
$("#cmnt-42").click(function(){
	viewcomment("42");
});
$("#cmnt-43").click(function(){
	viewcomment("43");
});
$("#cmnt-44").click(function(){
	viewcomment("44");
});
$("#cmnt-45").click(function(){
	viewcomment("45");
});
$("#cmnt-46").click(function(){
	viewcomment("46");
});
$("#cmnt-47").click(function(){
	viewcomment("47");
});
$("#cmnt-48").click(function(){
	viewcomment("48");
});
$("#cmnt-49").click(function(){
	viewcomment("49");
});
$("#cmnt-50").click(function(){
	viewcomment("50");
});